name: tekartik_tone_js
version: 0.6.1
description: tone js wrapper
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  js: any
  synchronized:
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8'
dev_dependencies:
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.6.5'
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_browser
    version: '>=0.4.8+1'
  test: '>=1.2.0'
  dev_build: '>=1.0.0'
  build_runner: '>=0.10.1'
  build_test: '>=0.10.3'
  build_web_compilers: '>=0.4.2'
  process_run:
